-- Michael_Cassar_1HND6S_SectionF

-- Setting ON DELETE SET NULL

ALTER TABLE TOWN
DROP CONSTRAINT TOWN_COUNTRYFK_FK;

ALTER TABLE TOWN
DROP CONSTRAINT TOWN_COUNTRYFK_NN;

ALTER TABLE TOWN
MODIFY (CountryFK NUMBER(4)
           CONSTRAINT TOWN_COUNTRYFK_FK
           REFERENCES COUNTRY(Country_ID)
           ON DELETE SET NULL);
  
-- Setting ON DELETE SET NULL
           
ALTER TABLE STREET
DROP CONSTRAINT STREET_TOWNFK_FK;

ALTER TABLE STREET
DROP CONSTRAINT STREET_TOWNFK_NN;

ALTER TABLE STREET
MODIFY (TownFK NUMBER(4)
           CONSTRAINT STREET_TOWNFK_FK
           REFERENCES TOWN(Town_ID)
           ON DELETE SET NULL);
           
-- Setting ON DELETE SET NULL

ALTER TABLE USERACCOUNT
DROP CONSTRAINT USERACCOUNT_USERROLEFK_FK;

ALTER TABLE USERACCOUNT
DROP CONSTRAINT USERACCOUNT_USERROLEFK_NN;
    
ALTER TABLE USERACCOUNT
MODIFY (UserRoleFK NUMBER(4)
           CONSTRAINT USERACCOUNT_USERROLEFK_FK
           REFERENCES USERROLE(Role_ID)
           ON DELETE SET NULL);           

-- Dropping Tables without purging
    
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE COUNTRY CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE ITEMCATEGORY CASCADE CONSTRAINTS;
DROP TABLE ORDERITEM CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE PERSON CASCADE CONSTRAINTS;
DROP TABLE STORE CASCADE CONSTRAINTS;
DROP TABLE STREET CASCADE CONSTRAINTS;
DROP TABLE TOWN CASCADE CONSTRAINTS;
DROP TABLE USERACCOUNT CASCADE CONSTRAINTS;
DROP TABLE USERROLE CASCADE CONSTRAINTS;

-- Dropping Views

DROP VIEW GUESTACCOUNTS;
DROP VIEW PERSONDETAILS;

-- Dropping Sequences

DROP SEQUENCE CLIENT_SEQUENCE;
DROP SEQUENCE COUNTRY_SEQUENCE;
DROP SEQUENCE EMPLOYEE_SEQUENCE;
DROP SEQUENCE ITEM_SEQUENCE;
DROP SEQUENCE ITEMCATEGORY_SEQUENCE;
DROP SEQUENCE ORDER_SEQUENCE;
DROP SEQUENCE PERSON_SEQUENCE;
DROP SEQUENCE STORE_SEQUENCE;
DROP SEQUENCE STREET_SEQUENCE;
DROP SEQUENCE TOWN_SEQUENCE;
DROP SEQUENCE USERACCOUNT_SEQUENCE;
DROP SEQUENCE USERROLE_SEQUENCE;
DROP SEQUENCE DEPARTMENT_SEQUENCE;

-- Flashing back tables

FLASHBACK TABLE USERROLE TO BEFORE DROP;
FLASHBACK TABLE USERACCOUNT TO BEFORE DROP;
FLASHBACK TABLE TOWN TO BEFORE DROP;
FLASHBACK TABLE STREET TO BEFORE DROP;
FLASHBACK TABLE STORE TO BEFORE DROP;
FLASHBACK TABLE PERSON TO BEFORE DROP;
FLASHBACK TABLE ORDERS TO BEFORE DROP;
FLASHBACK TABLE ORDERITEM TO BEFORE DROP;
FLASHBACK TABLE ITEMCATEGORY TO BEFORE DROP;
FLASHBACK TABLE ITEM TO BEFORE DROP;
FLASHBACK TABLE EMPLOYEE TO BEFORE DROP;
FLASHBACK TABLE DEPARTMENT TO BEFORE DROP;
FLASHBACK TABLE COUNTRY TO BEFORE DROP;
FLASHBACK TABLE CLIENT TO BEFORE DROP;

-- Recreating Views

CREATE OR REPLACE FORCE VIEW GUESTACCOUNTS
AS
  SELECT username,
         password,
         role_id
  FROM USERACCOUNT UA
  JOIN USERROLE UR
  ON (UA.userrolefk = UR.role_id)
  WHERE LOWER(UR.role_name) = 'guest'
  WITH CHECK OPTION
    CONSTRAINT GUESTACCOUNTS_CO;
    
CREATE OR REPLACE FORCE VIEW PERSONDETAILS
AS
  SELECT p.firstname,
         p.lastname,
         p.date_of_birth,
         p.contact_number,
         p.residence_name,
         s.streetname,
         t.townname,
         co.country_name
  FROM PERSON p
  JOIN STREET s
  ON (p.streetfk = s.streetid)
  JOIN TOWN t
  ON (s.townfk = t.town_id)
  JOIN COUNTRY co
  ON (t.countryfk = co.country_id)
  WITH READ ONLY
    CONSTRAINT PERSONDETAILS_RO;
    
-- Recreating sequences

CREATE SEQUENCE USERROLE_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 10;

CREATE SEQUENCE USERACCOUNT_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 60;

CREATE SEQUENCE ORDER_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 60;

CREATE SEQUENCE ITEM_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 30;

CREATE SEQUENCE ITEMCATEGORY_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 10;

CREATE SEQUENCE DEPARTMENT_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 10;

CREATE SEQUENCE STORE_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 5;

CREATE SEQUENCE TOWN_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 10;

CREATE SEQUENCE COUNTRY_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 10;

CREATE SEQUENCE PERSON_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 60;

CREATE SEQUENCE EMPLOYEE_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 30;

CREATE SEQUENCE CLIENT_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 30;

CREATE SEQUENCE STREET_SEQUENCE
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOMINVALUE
  NOCYCLE
  CACHE 30;